language: ruby
rvm: 2.5.0
cache: bundler


before_script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate

script:
 - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: 12345
  on:
    repo: fetc90/acebook-Spacebook

after_script:
 - bundle exec rake coveralls:push

#
# language: ruby
# rvm:
# - 2.5.0
# cache: bundler
# services:
#   - postgresql
# before_script:
#   - bundle exec rake db:create
#   - bundle exec rake db:migrate
# script: bundle exec rspec
