language: ruby
rvm:
 - 2.5
 - jruby

 before_install:
- gem install bundler 

 before_script:
 - bundle exec rails db:create RAILS_ENV=test
 - bundle exec rails db:migrate RAILS_ENV=test

script:
 - bundle exec rspec

after_script:
- bundle exec rake coveralls:push