language: ruby
rvm:
 - 2.5
 - jruby

 before_install:
 - gem install bundler:1.16.6
#  - bundle update --bundler

 deploy:
   provider: heroku
   api_key: 
   secure: "a1B2c3D4e5F6"

 before_script:
 - bundle exec rails db:create RAILS_ENV=test
 - bundle exec rails db:migrate RAILS_ENV=test

script:
 - bundle exec rspec

after_script:
 - bundle exec rake coveralls:push