language: ruby
rvm: 2.5.0
cache: bundler 

before_script:
 - gem update --system
 - gem install bundler
 - bundle exec rake db:create
 - bundle exec rake db:migrate

script:
 - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: Is/e56C/GyZidu+qOBSDUQNs086bGTrVryPkfRCQfQT5cMAYRnZNV+DnQDqib/BwbWsxcW+JbPqi8zhYoMW7dfGE1Pfy3cH2NlM//uCFTEkmLbpAZjs5fCjexq6EyL4XIv8J8tlFSqMDmifjdB/I/bK44kgfzKQQNs3R5Uq3siA3Psx2X0UBcSnsDvWSE3PZ/dXbEJclOsztxaobjHeysBgK2SnJLiV0GeuKWGibQ7Vqu6tgBur9mETUvn33E4xVM3kClASq/OL+Pf7JPCYKerC0YDvkOjSnP5UXKfCqyNLxpYInNB9EbKtW+QlPLBaKWoAEWSiH/m2SSuV0tAJ0KXLkPKRW060DsiLkV4bOj1aBrwBxh/BZbXGpVTkOeDzR/BcrUyQHQjtTPSYYqk6rbmchuioGohT99Bb+5L0TjQpRjD7ovurv7uRFEHf3A//YbnCIjZ5J6KTE/Nbx5xpML905CgTgPL938ogR4qh3qtoyWqhB0WV9HbAVFy9fCRzlVUXulby5k6fvrYl5jUdz2U4xyeEkaECRlaB3bbGUXfjWOA7zRdiIk9FO4PmOSJaDTQpunN23SXLdFJPjvCUx1i8a6iNSQ98MXxbT5fset+1Rw+c08abiswv6U/6so9ltgmBigkv7xdMAhGwVWx92n1xhItJDQXPF9Fifac+X+jM=
  app: acebook-spacebook
  on:
    repo: fetc90/acebook-spacebook

after_script:
 - bundle exec rake coveralls:push

# language: ruby
# rvm:
# - 2.5.0
# cache: bundler
# services:
#   - postgresql
# before_script:
#   - bundle exec rake db:create
#   - bundle exec rake db:migrate
# script: bundle exec rspec

